### ISSUE TITLE
How to implement partial replication?

### ISSUE THREAD

**Issue by wdd00** [roohitavaf/DKVF#2]
The platform has already implemented partitioned and replicated data stores. How to implement partial replication? For example, I specify the key range of each server in the config file. How to make sure keys to locate in corresponding servers during initializing the storage engines?Maybe I can use the client's put operations to insert these keys. 

Then what about YCSB workloads? Will the YCSB client insert keys not belonging to the corresponding key range in the server?

**Comment by roohitavaf** [comment]
DKVF does not enforce any partitioning/replication policy. So you are free to distribute your data any way you like. You have to implement your partitioning logic in your client and server code. DKVF simply streamlines for your storage and communication.

For example, consider this https://github.com/roohitavaf/DKVF/blob/master/Eventual_client/src/edu/msu/cse/eventual/client/EventualClient.java
In this client,  the client has a `dcId` in its configuration that specifies the local DC for this client. Then, I am assuming a full replica with a simple hash-based partitioning. So, I use the `dcId` and partition number given by `findPartition` function. These all depend on you. If you like to have ranges, you have to define these ranges for your client, and use them in your client logic. 

Once you implemented your partitioning and replication logic in your client code, YCSB will use your client code (via the driver). So, YSCDB requests will be directed to the right servers based on your logic.
