### ISSUE TITLE
How to assign a list of values to keys in protocol properties? 

### ISSUE THREAD

**Issue by wdd00** [roohitavaf/DKVF#3]
When I use the ClusterDesigner.jar to create a server, how to assign a list of values to a key in the protocol properties? Should all values in the same value block with some delimiter? If yes, what is the delimiter? Could you show me how you design "children_p_ids" in the server parameter?
Thanks very much.

**Comment by roohitavaf** [comment]
Yes, use "," to separate your IDs. 
Look at the config reader code here:
https://github.com/roohitavaf/DKVF/blob/4aa8f847dbf68eb1c0a817172d8f52fa28203bab/DKVF_core/src/edu/msu/cse/dkvf/config/ConfigReader.java#L194

For any key, you can set a comma-separated string as a value.

**Comment by wdd00** [comment]
Thank you very much.
