### ISSUE TITLE
How to setup the project for development

### ISSUE THREAD

**Issue by danielporto** [roohitavaf/DKVF#5]
I watched the videos and follow the instructions to build a working version of
the eventual server/client deployment. 
However, copying/paste sources to build the project is not very clean way. I could change the project
structure, but that would make it hard to contribute with the original source. 
I wonder how do you set up your development environment.
Even trying with Eclipse, I got many circular references that makes it impossible to build without the copying paste.

Ex. core depends on  server which depends on core again.
The video propose copy core into server source (similarly copy into client source and tools source in order to build).

**Comment by roohitavaf** [comment]
Yes, it may not be the most elegant way, but it should work if you follow steps demonstrated in the videos.
